### ISSUE TITLE
Resource objects should have plural type names and always be arrays

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/openbel-server#13]
The problem was raised by @nbargnesi that the [completions responses](http://next.belframework.org/api/expressions/p%28HGNC:/completions) do not lend themselves to object mapping in javascript. You end up with property chains like `completion.completion.value`.

Instead let's design our resource objects and json response objects with the following in mind:

- resource object names are plural
  - one set of names
  - unique type within a json object (versus having a `post` and `posts` key)
- resource object values are always arrays
  - one code path needed for both serialization and deserialization

An example of this approach is [here](https://gist.github.com/abargnesi/5054e0a2730778d11eb4).

Some discussion from the JSON API folks:
https://github.com/json-api/json-api/issues/268

**Comment by nbargnesi** [comment]
+1

From a client perspective, it's more verbose than necessary regardless of the client's language. I like the proposal.

**Comment by abargnesi** [comment]
These fixes do not apply when the server is rendering *application/hal+json*.
