### ISSUE TITLE
Annotations API

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/openbel-server#14]
Implement:

### Implement (order of importance):

- GET */api/annotations*
  - traits: *filterable*, *facetable*
- GET */api/annotations/{annotation}*
- GET */api/annotations/{annotation}/values*
  - traits: *filterable*, *facetable*
- GET */api/annotations/{annotation}/values/{value}*

### Notes

- Initial stubs and then fill with RDF data.

**Comment by abargnesi** [comment]
@ncatlett Do we have RDF data for annotations concept schemes and their values?

**Comment by ncatlett** [comment]
not yet

**Comment by abargnesi** [comment]
Refer to notes on wiki: http://wiki.openbel.org/display/BEL2RDF/Annotations
