### ISSUE TITLE
Update biological_context sub-schema for Evidence.

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/openbel-server#37]
The biological_context sub-schema in the [evidence schema](http://next.belframework.org/schema/evidence.schema.json) is currently defined as:

```json
biological_context": {
    "type": "object",
    "title": "Biological Context",
    "description": "A biological context specifies the experiment's parameters where this interaction was observed.",
    "additionalProperties": true,
    "properties": {
        "species": {
            "type": "string",
            "title": "Species from NCBI Taxonomy",
            "description": "The id (i.e. 9606), scientific name (i.e. Homo sapiens), and common name (i.e. man, human) are allowed values."
        }
    }
}
```

We should update the biological_context sub-schema to declare *string to string annotations* (e.g. single annotation value) as well as *string to array of string* (e.g. multiple annotation values).

Updates:

1. Use a `oneOf` to allow:
  -  *string to string*
  -  *string to array of string*. The *array of string* should have a *minItems* of 0 to be flexible.
  -  *string to JSON null*
2. Changes in (1) should apply to the *species* property as well. 

refs #12

**Comment by wshayes** [comment]
Going to remove the specific properties in the biological_context section (e.g. species) and recommend using oneOf [{name, value(s)}, {uri(s)}].  The name should match up to the names in the http://next.belframework.org/api/annotations listing.  This also means that we should have an easy way to resolve the URI's to the name, value, desc, etc information.

**Comment by nbargnesi** [comment]
I can't create evidence with this schema change in place. Different errors are kicked back depending on validator implementation - all seem to indicate this violates the ``oneOf`` [here](https://github.com/OpenBEL/openbel-server/blob/6c01a0f1dec0c8ef27e86ccf0437e3d7b293d728/docs/schemas/evidence.schema.json#L80). Maybe because each element in the ``oneOf`` is an object?

Looking at it briefly - maybe changing the schema to push the biological context object constraints into a single object is the way to go.

:boom: The server API response:
```json
{
  "status":400,
  "msg":"#/evidence/biological_context/1: failed schema #/properties/evidence/properties/biological_context/items: More than one subschema in \"oneOf\" matched."
}
```

Another validator (z-schema):
```bash
[
    {
        "code": "ONE_OF_MULTIPLE",
        "params": [],
        "message": "Data is valid against more than one schema from 'oneOf'",
        "path": "#/evidence/biological_context/1"
    }
]
```

**Comment by nbargnesi** [comment]
Here's a ``biological_context`` block that will trigger the 400:

```json
...
"biological_context" : [
         {
            "name" : "Species",
            "value" : 9606
         },
         {
            "name" : "Cell",
            "value" : "fibroblast"
         }
      ],
...
```

**Comment by abargnesi** [comment]
The validation issue is with the valve oneOf. A "required" property is
needed otherwise both schemas match.

**Comment by abargnesi** [comment]
The original schema is sufficient if you provide:

```json
"required": [ "name", "value" ]
```

for the first oneOf.

For the second oneOf you need:

```json
"required": [ "uri" ]
```

Then the schemas will differentiate, satisfying the oneOf.

**Comment by wshayes** [comment]
Thanks Tony - does anyone have a set of evidences already configured to test this?  Otherwise, I'll write a script to create some to test the schema.

**Comment by abargnesi** [comment]
There is an archive on next.bel framework.org for evidence from the large
corpus. This only has name / value annotations though.
