### ISSUE TITLE
Is name unique within a biological_context for an evidence?

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/openbel-server#46]
When working on OpenBEL/openbel-server#43 (mapping annotations to name/value) there is a real potential for name collisions.

For example if I have three free annotations `P-value`, `P value`, and `PValue` then the names will all normalize to `PValue`.

Another example that maps to the same name (`Cell Line Ontology) would be:
```json
{
    "uri": "http://next.belframework.org/api/annotations/cell-line-ontology/values/0001045"
},
{
    "name": "Cell Line Ontology",
    "value": "11-5.2.1.9 cell"
}
```

@nbargnesi @wshayes Should we enforce uniqueness of names or rather collapse common names to an array of values?

**Comment by abargnesi** [comment]
It seems like a no-brainer to collapse values by name since we cannot easily enforce this at the schema level.

**Comment by nbargnesi** [comment]
Not sure I get what you're asking.

I would expect this evidence context:
```json
{
  "evidence": {
    ...
    "biological_context": [
      {
        "name": "foo",
        "value": "bar"
      },
      {
        "name": "foo",
        "value": "baz"
      }
    ],
    ...
}
```

To be equivalent to:
```json
{
  "evidence": {
    ...
    "biological_context": [
      {
        "name": "foo",
        "value": ["bar", "baz"]
      }
    ]
    ...
}
```

So unique in terms of the same names being eligible for collapsing? If that's the case, I think collapsing makes sense.

**Comment by abargnesi** [comment]
Yes. That is exactly what I meant and your example captures it nicely.

It is also possible for
```json
{
  "uri": "http://..."
}
```
to map to the `foo` annotation as well.

Thanks. I will collapse biological context names when processing evidence data.
