### ISSUE TITLE
Rename biological_context to experiment_context within evidence schema.

### ISSUE THREAD

**Issue by nbargnesi** [OpenBEL/openbel-server#51]
I'm talking about the schema and API specifically here whose audience is largely made up of integrators, engineers, developers, etc.

We're talking about knowledge representing the existence of biological entities and the relationships between them. The "*biological*" qualifier on context is implied under most circumstances(see :one: below).

For example:
```json
"biological_context": [
  { "name": "Cell", "value": "cardiac muscle cell" },
  { "name": "Species", "value": 9606 }
]
```  

That "*biological_*" prefix is redundant.

--
:one: The annotations stored in ``biological_context`` **aren't required to be biological in nature**. We have examples like the following:

```json
"biological_context": [
  { "name": "Species", "value": 29062 },
  { "name": "curatedBy", "value": "nlp" },
  { "name": "nlpCurator", "value": "GENIA" }
]
```

Using "*context*" here is more to the point.

**Comment by nbargnesi** [comment]
@wshayes @abargnesi thoughts?

**Comment by abargnesi** [comment]
If we rename *biological_context* to *context* then it might obscure when one would use it over *metadata*. I think *curatedBy* and *nlpCurator* are better suited in metadata, because they are not curated directly from the article.

**Comment by nbargnesi** [comment]
Concede the point about *curatedBy* and *nlpCurator*. I'll put forth *foundIn* instead. This annotation captures what section of a paper the evidence is found in (i.e., the *context*). It's values might be ``abstract``, ``introduction``, and ``results``.

```json
"biological_context": [
  { "name": "Species", "value": 29062 },
  { "name": "foundIn", "value": "abstract" }
]
```

So again, annotations in ``biological_context`` **aren't required to be biological in nature** and there are annotations that **are context** that have no place in metadata.

**Comment by ncatlett** [comment]
Can we rename biological_context to experiment_context? My feeling is that the context annotations should reflect the experiment information (which may not be "biological") and the metadata should reflect information about the curation.
