### ISSUE TITLE
Represent evidence biological context annotations as URIs

### ISSUE THREAD

**Issue by nbargnesi** [OpenBEL/openbel-server#70]
Our [evidence schema](http://next.belframework.org/schema/evidence.schema.json) requires biological context as objects with either a ``name`` and ``value`` property or a ``uri`` property. We talked at various times of using the latter ``uri`` variant when a controlled ("structured") annotation is being used.

Regardless of input, the current evidence representation in responses always uses the ``name`` and ``value`` annotation variant.

A good solution would be to see the ``uri`` variant if that was how the evidence was created. A better solution would be to see the ``uri`` variant if it exists, *regardless* of how the evidence was created. In this latter solution, with the following annotations as input to evidence creation:

```json
  ...
  "biological_context": [
    {"name": "Species", "value": 9606},
    {"uri": "http://next.belframework.org/api/annotations/taxon/values/9606"}
  ]
  ...
```

The response would *always be*:

```json
  ...
  "biological_context": [
    {"uri": "http://next.belframework.org/api/annotations/taxon/values/9606"}
  ]
  ...
```

**Comment by abargnesi** [comment]
@nbargnesi The example annotation objects in the "biological_context" request are not equivalent because "Species" will not resolve to "Ncbi Taxonomy" as defined.

I think a more inclusive example that shows the behavior might be:

```json
...
"biological_context": [
    {"name": "Species", "value": 9606},
    {"name": "Taxon",   "value": 9606},
    {"uri": "http://next.belframework.org/api/annotations/taxon/values/9606"}
]
...
```

For this the respond should be:
```json
...
"biological_context": [
    {"name": "Species", "value": 9606},
    {"uri": "http://next.belframework.org/api/annotations/taxon/values/9606"}
]
...
```

The *Taxon* object mapped to the URI and was de-duplicated. The *Species* object does not map to that URI so it remains an unstructured object in the biological_context.

Does this jive with your expectations?

**Comment by abargnesi** [comment]
@wshayes and I discussed returning a structured annotation (e.g. one with a `uri`) with `name` and `value` data. The `name` and `value` will reflect the preferred labels for the ConceptScheme and Concept (i.e. `Disease Ontology` and `Sly syndrome`).

Showing the name and value along with the URI is a convenience to the client. A client would then not need to retrieve each annotation to display evidence.

@nbargnesi thoughts?

**Comment by nbargnesi** [comment]
Sounds good to me.

**Comment by abargnesi** [comment]
Thanks. Change to include name/value with structured annotation (e.g. `uri` present) is now deployed to `next.belframework.org`.
