### ISSUE TITLE
/api/evidence GET statistics

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/openbel-server#75]
Would be helpful to get total number of evidence documents, search result number of documents, current page of documents and number of evidence documents returned so we can present this in the search results page.

**Comment by abargnesi** [comment]
Need to create robust API test and then factor out paging functionality.

**Comment by abargnesi** [comment]
Here is an example of the paging statistics object. Let me know if you have improvements to the property naming.

```json
"metadata": {
  "collection_paging": {
    "total": 42057,
    "filtered_total": 42057,
    "page_total": 421,
    "current_page": 2,
    "current_resource_total": 100
  }
}
```

**Comment by abargnesi** [comment]
Updated naming and added some title/description to the schema. Now it is like:

```json
  "metadata": {
    "collection_paging": {
      "total": 42057,
      "total_filtered": 42057,
      "total_pages": 421,
      "current_page": 2,
      "current_page_size": 100
    }
  }
```
