### ISSUE TITLE
Grouping facets

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/openbel-server#76]
Can you group /api/evidence facets like this instead?  Preferably reverse-sort ordered by count as seen below.

    {
      "category": "experiment_context",
      "name": "Ncbi Taxonomy",
      "values": [ {
          "value": "Homo sapiens",
          "filter": "{\"category\":\"experiment_context\",\"name\":\"Ncbi Taxonomy\",\"value\":\"Homo sapiens\"}",
          "count": 27070
      },
      {
          "value": "Mus musculus",
          "filter": "{\"category\":\"experiment_context\",\"name\":\"Ncbi Taxonomy\",\"value\":\"Mus musculus\"}",
          "count": 10647
       },
      {
          "value": "Rattus norvegicus",
          "filter": "{\"category\":\"experiment_context\",\"name\":\"Ncbi Taxonomy\",\"value\":\"Rattus norvegicus\"}",
          "count": 4337
       }]
    }

**Comment by wshayes** [comment]
{
      "category": "experiment_context",
      "name": "Ncbi Taxonomy",
      "values": [
        {
          "value": "Homo sapiens",
          "filter": "{\"category\":\"experiment_context\",\"name\":\"Ncbi Taxonomy\",\"value\":\"Homo sapiens\"}",
          "count": 27070
        },
        {
          "value": "Mus musculus",
          "filter": "{\"category\":\"experiment_context\",\"name\":\"Ncbi Taxonomy\",\"value\":\"Mus musculus\"}",
          "count": 10647
        },
        {
          "value": "Rattus norvegicus",
          "filter": "{\"category\":\"experiment_context\",\"name\":\"Ncbi Taxonomy\",\"value\":\"Rattus norvegicus\"}",
          "count": 4337
        },
        {
         *"value": "[\"9606\", \"9606\"]",
          "filter": "{\"category\":\"experiment_context\",\"name\":\"Ncbi Taxonomy\",\"value\":\"[\\\"9606\\\", \\\"9606\\\"]\"}",
          "count": 2
        }*
      ]
    },

**Comment by abargnesi** [comment]
This reflects the data. There are exactly two BEL evidences in the large corpus dataset that contain a *Species* annotation defined as:

    SET Species = {"9606", "9606"}

lines 33619 and 129199 of [large_corpus.bel](https://github.com/OpenBEL/openbel-framework-resources/blob/e97645cd69ab2639e8ddb3e8bf48bb06d7cec136/knowledge/large_corpus.bel?raw=true)

**Comment by wshayes** [comment]
Yes - I realized afterwards away from my computer that this is an excellent example of something that is easy to fix with the BEL Mgr (and notice).  Sorry I didn’t update the ticket.

**Comment by abargnesi** [comment]
It's worth nothing that a multi-value annotation is perfectly legal though in this situation it's redundant.

Do you think a multi-value annotation should be treated as a single facet value with two members or two facet values? If we want the latter then the server should split them on create or update of an evidence.

**Comment by wshayes** [comment]
Single facet value for now.  I don’t see a need fro multiple-value facets in general so we’ll review if it becomes an issue.
