### ISSUE TITLE
Creating evidence (POST /api/evidence) may not conform to evidence schema

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/openbel-server#78]
BEL formats are converted into Evidence JSON schema which currently doesn't conform to http://next.belframework.org/schema/evidence.schema.json.

- ~~Make citation.authors an array or null~~
- ~~Metadata needs to be objects with name/value (optional uri) properties~~
- ~~Metadata object items should be allowed~~
- ~~Return single evidence resources as object instead of array~~
- ~~The references section should be added, but treated as an unchecked object (for now)~~

**Comment by abargnesi** [comment]
Fixed. Now working on rebuilding BEL evidence from public corpora. Will update on *next.belframework.org* later today.

**Comment by abargnesi** [comment]
An example of an `evidence-collection` resource and an `evidence` resource are provided in [this gist](https://gist.github.com/abargnesi/63fd5ee5a0ae76b7a33e).

An `evidence` resource is a JSON object with an `evidence` property and the `evidence-collection` resource holds zero or more of these `evidence` resources.

Additionally the `facets` property has been removed *from each evidence resource* since this is implementation data not useful to the client. The `facets` property still remains on the outer JSON object.

@wshayes How does this representation look? Will it improve client-side processing?

**Comment by wshayes** [comment]
The approach and gist looks good to me.

**Comment by abargnesi** [comment]
Ok, thanks. This approach has been deployed to **next.belframework.org**. For example look at the documentation example for [GET /api/evidence](http://next.belframework.org/docs.html#evidence_get).
I am missing documentation for */api/namespaces* and the examples are incorrect for */api/annotations/...*.

**Comment by abargnesi** [comment]
Documentation is complete for this, closing.
