### ISSUE TITLE
Can you add the annotation name to api/annotations/values search results?

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/openbel-server#79]
In order to present the autocompletion results for the annotation field in the BEL Mgr, I need both the common name for the annotation namespace and the preferred term for the annotation value.  (I assume that the annotation value name is the preferred term.)  Can you add the annotation name to the annotation value results?  Otherwise, I'll have to search for the annotation values and then follow it up immediately with a query for each annotation to determine the common name for each.

**Comment by abargnesi** [comment]
The `annotation_value.name` property does represents the preferred name of the annotation. For example run [this search](http://next.belframework.org/api/annotations/taxon/values?filter={%22category%22:%22fts%22,%22name%22:%22search%22,%22value%22:%22Mouse%22}) and you will see the following response:

```json
{
  "annotation_values": [
    {
      "type": "SpeciesAnnotationConcept",
      "identifier": "10090",
      "name": "Mus musculus",
      "_links": {
        "self": {
          "type": "annotation_value",
          "href": "http://next.belframework.org/api/annotations/ncbi-taxonomy/values/10090"
        },
        "collection": {
          "type": "annotation",
          "href": "http://next.belframework.org/api/annotations/ncbi-taxonomy"
        }
      }
    }
  ]
}
```

Notice `_links.collection` holds the location of the annotation_value's collection (i.e. the `annotation resource`).

This enhancements seems related to https://github.com/OpenBEL/openbel-server/issues/38.

**Comment by wshayes** [comment]
Yes - same issue - didn't see it. Happy to close this one in favor of #38.
