### ISSUE TITLE
Add query term match in annotation and namespace results

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/openbel-server#80]
Need to have the query term used in the annotation and namespace value searches both the prefixed and un-prefixed queries (e.g. with or without namespace HGNC or annotation set identifier).  It doesn't look like the API Docs are created for /api/namespace GET requests.

Related to #38

**Comment by abargnesi** [comment]
Can you provide a full query example with expected response? It is unclear what you're asking.

**Comment by wshayes** [comment]
Note the search value of 'epitheliod' and the *matched* value in the result of 'epithelioid Thymoma'.   This should be available in /api/annotations/values and /api/annotations/{annotation}/values as well as /api/namespaces/values and /api/namespaces/{namespace}/values.

Search query:
     {
        "category": "fts",
        "name": "search",
        "value": "epitheliod"
     }

Result:
    {
      "annotation_values": [
        {
          "type": "BiologicalProcessConcept",
          "identifier": "3282",
          "matched": "epithelioid Thymoma",
          "name": "dendritic cell thymoma",
          "_links": {
            "self": {
              "type": "annotation_value",
              "href": "http://next.belframework.org/api/annotations/disease-ontology/values/3282"
            },
            "collection": {
              "type": "annotation",
              "href": "http://next.belframework.org/api/annotations/disease-ontology"
            }
          }
        }
      ]
    }

**Comment by abargnesi** [comment]
Enhanced annotation APIs with `match_text` property. See [API documentation](http://next.belframework.org/docs.html).

A [search](http://next.belframework.org/api/annotations/do/values?filter={%22category%22:%22fts%22,%22name%22:%22search%22,%22value%22:%22epithelioid%22}) for `epithelioid` under the disease ontology yields:

```json
  annotation_value": {
    "type": "BiologicalProcessConcept",
    "identifier": "6193",
    "name": "epithelioid sarcoma",
    "match_text": "<<epithelioid>> cell sarcoma <<epithelioid>> sarcoma (morphologic abnormality)",
    "_links": {
      "self": {
        "type": "annotation_value",
        "href": "http://next.belframework.org/api/annotations/disease-ontology/values/6193"
      },
      "collection": {
        "type": "annotation",
        "href": "http://next.belframework.org/api/annotations/disease-ontology"
      }
    }
  }
```

The namespaces API will be updated next following the same design.

**Comment by wshayes** [comment]
Thanks - that looks great.
